enum LinerColor {
  "gradeGrey" = "liner-color-grade-grey",
  "witchingHour" = "liner-color-witching-hour",
  "darkOcean" = "liner-color-dark-ocean",
  "eveningSunshine" = "liner-color-evening-sunshine",
  "piggyPink" = "liner-color-piggy-pink",
  "sunrise" = "liner-color-sunrise",
  "yoda" = "liner-color-yoda",
  "flare" = "liner-color-flare",
  "neuromancer" = "liner-color-neuromancer",
  "amin" = "liner-color-amin",
  "metapolis" = "liner-color-metapolis",
  "harvey" = "liner-color-harvey",
  "aquaMarine" = "liner-color-aqua-marine",
  "aubergine" = "liner-color-aubergine",
  "bloodyMary" = "liner-color-bloody-mary",
  "mangoPulp" = "liner-color-mango-pulp",
  "frozen" = "liner-color-frozen",
  "roseWater" = "liner-color-rose-water",
  "horizon" = "liner-color-horizon",
  "coolBlues" = "liner-color-cool-blues",
  "monteCarlo" = "liner-color-monte-carlo",
  "megaTron" = "liner-color-mega-tron",
  "moonlitAsteroid" = "liner-color-moonlit-asteroid",
  "jShine" = "liner-color-j-shine",
  "coolSky" = "liner-color-cool-sky",
  "azurLane" = "liner-color-azur-lane" ,
  "memariani" = "liner-color-memariani"
}

export default LinerColor;